name = "lewsicraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb0e3658455702c8f361d51ae0fe59eeb3a0ff820e809700d7ec2b2add87f115"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
